CREATE TABLE IF NOT EXISTS users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email            VARCHAR(100)                            NOT NULL,
    name             VARCHAR(300)                            NOT NULL,
    date_of_creation TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    password         VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS quotes
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content           TEXT                                    NOT NULL,
    modification_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    author_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_quotes PRIMARY KEY (id),
    CONSTRAINT fk_quotes_on_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS votes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    likes     BOOLEAN,
    dislikes  BOOLEAN,
    author_id BIGINT                                 NOT NULL,
    quotes_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_votes PRIMARY KEY (id),
    CONSTRAINT fk_votes_on_users FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_votes_on_quotes FOREIGN KEY (quotes_id) REFERENCES quotes (id)
);




